# Generated by Django 5.1.3 on 2025-01-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_author_alter_post_content_alter_post_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image_name',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
